import { MedusaError } from '@medusajs/framework/utils'
import type {
  AuthTypes,
  Context,
  Logger,
} from '@medusajs/framework/types'
import { AuthVerification } from '@medusajs/auth/dist/models'
import {
  deriveHmacKey,
  generateOtpCode,
  normalizeCode,
  digestCode,
} from '../../lib/otp-code.cjs'

// 6-digit numeric one-time-code verification provider.
//
// Medusa's built-in `token` provider emits a 43-character base64url token and
// stores only `sha256(token)` (unsalted). The email relay used to strip every
// non-digit from that token (`.replace(/[^0-9]/g, '')`), which usually produced a
// plausible-looking 6-digit code that could never match the stored hash — so a
// customer could never actually confirm their code. This provider replaces that
// with a real 6-digit OTP generated by a CSPRNG, stored behind a keyed HMAC so a
// leaked row cannot be brute-forced (there are only 1,000,000 possible codes, so
// a bare sha256 of the code is NOT acceptable).
//
// Security contract (per Owner decision):
//   - the code is 6 digits, 000000–999999, uniformly random, drawn from
//     `crypto.randomInt` (CSPRNG) and zero-padded to 6 digits.
//   - the stored digest is HMAC-SHA256 over the code, keyed by a domain-separated
//     key derived from `JWT_SECRET`. The plaintext code is never persisted and
//     never written to any log or audit record.
//   - TTL 15 minutes (900s), one-time use, resend invalidates the prior code.
//   - the code leaves the server ONLY through the `auth.verification_requested`
//     event payload (the email subscriber renders it), never in an HTTP response:
//     the request workflow strips `code`/`expires_at` from the response.
//
// No new migration: the provider reuses the existing `auth_verification` table's
// `provider_metadata` JSONB column to store the HMAC digest, exactly like the
// built-in token provider stores its `token_hash`.

const DEFAULT_TTL_SECONDS = 900 // 15 minutes

type Options = {
  // Base secret used to derive the HMAC key. Supplied by the module wiring from
  // `JWT_SECRET` (already validated as a 32-byte hex secret in the policy layer).
  hmac_secret?: string
  ttl_seconds?: number
}

type InjectedDependencies = {
  logger?: Logger
  authVerificationService: {
    list: (filters: Record<string, unknown>, config: Record<string, unknown>, sharedContext?: Context) => Promise<VerificationRow[]>
    create: (data: Record<string, unknown>, sharedContext?: Context) => Promise<Record<string, unknown>>
    update: (data: Record<string, unknown>, sharedContext?: Context) => Promise<Record<string, unknown>>
  }
  // The auth module's MikroORM base repository, used to run the atomic
  // conditional claim (UPDATE ... WHERE verified_at IS NULL) that closes the
  // confirm check-then-update race the built-in token provider also has.
  baseRepository?: {
    getActiveManager: (context?: Context) => {
      nativeUpdate: <E extends object>(entityName: E, where: Record<string, unknown>, data: Record<string, unknown>) => Promise<number>
    }
  }
}

type VerificationRow = {
  id: string
  auth_identity_id: string
  entity_id: string
  entity_type: string
  code_provider: string
  provider_metadata?: Record<string, unknown> | null
  verified_at?: Date | null
  requested_at: Date
}

// Drop the internal `provider_metadata` (which holds the keyed HMAC `code_hash`
// and the internal `requested_at` marker) from any object the provider returns.
// The workflow only strips `code`/`expires_at` from the HTTP response, so without
// this the digest would leak to the caller. The persisted row is never touched —
// only the in-memory return value is sanitized.
function stripProviderMetadata<T extends Record<string, unknown>>(row: T): Omit<T, 'provider_metadata'> {
  const { provider_metadata: _omitted, ...rest } = row
  return rest
}

class OtpVerificationProvider {
  static identifier = 'otp'

  private readonly logger_: Logger
  private readonly options_: Options
  private readonly hmacKey_: Buffer
  private readonly authVerificationService_: InjectedDependencies['authVerificationService']
  private readonly baseRepository_: InjectedDependencies['baseRepository']

  constructor(container: InjectedDependencies, options: Options = {}) {
    this.logger_ = container.logger ?? (console as unknown as Logger)
    this.options_ = options
    this.authVerificationService_ = container.authVerificationService
    this.baseRepository_ = container.baseRepository

    const secret = options.hmac_secret
    if (!secret || typeof secret !== 'string' || secret.length < 32) {
      throw new MedusaError(
        MedusaError.Types.INVALID_DATA,
        'OTP verification provider requires `hmac_secret` (a >=32-char secret) in its options.',
      )
    }
    this.hmacKey_ = deriveHmacKey(secret)
  }

  static validateOptions(options: Record<string, unknown>): void {
    const secret = options.hmac_secret
    if (!secret || typeof secret !== 'string' || secret.length < 32) {
      throw new MedusaError(
        MedusaError.Types.INVALID_DATA,
        'OTP verification provider option `hmac_secret` must be a string of at least 32 characters.',
      )
    }
    const ttl = options.ttl_seconds
    if (ttl != null && (!Number.isInteger(ttl) || (ttl as number) < 60 || (ttl as number) > 3600)) {
      throw new MedusaError(
        MedusaError.Types.INVALID_DATA,
        'OTP verification provider option `ttl_seconds` must be an integer between 60 and 3600.',
      )
    }
  }

  private ttlMs_(): number {
    return (this.options_.ttl_seconds ?? DEFAULT_TTL_SECONDS) * 1000
  }

  async request(data: AuthTypes.RequestAuthVerificationDTO, sharedContext: Context = {}): Promise<AuthTypes.RequestAuthVerificationResponse> {
    const existing = await this.authVerificationService_.list(
      {
        auth_identity_id: data.auth_identity_id,
        entity_id: data.entity_id,
        entity_type: data.entity_type,
      },
      { take: 1, skip: 0 },
      sharedContext,
    )

    // A request ALWAYS issues a fresh code, even for an already-verified identity.
    // The OTP is a one-time login factor (Phase 2), not a one-time registration
    // gate: a returning user must be able to request a new code on every sign-in.
    // The `existing.length` branch below therefore unconditionally resets
    // `verified_at` to null and overwrites `code_hash` with the new digest — the
    // prior code is invalidated and the new one becomes the only claimable code.
    // (The "already verified" dedup, if ever needed, belongs to the caller's
    // registration flow, never to this provider, which only mints codes.)

    const code = generateOtpCode()
    const digest = digestCode(this.hmacKey_, code)
    const requestedAt = new Date(Date.now())
    const expiresAt = new Date(requestedAt.getTime() + this.ttlMs_())

    let verification: Record<string, unknown>
    if (existing.length) {
      verification = await this.authVerificationService_.update(
        {
          id: existing[0].id,
          code_provider: data.code_provider,
          provider_metadata: { code_hash: digest, requested_at: requestedAt.toISOString() },
          requested_at: requestedAt,
          verified_at: null,
        },
        sharedContext,
      )
    } else {
      verification = await this.authVerificationService_.create(
        {
          auth_identity_id: data.auth_identity_id,
          entity_id: data.entity_id,
          entity_type: data.entity_type,
          code_provider: data.code_provider,
          provider_metadata: { code_hash: digest, requested_at: requestedAt.toISOString() },
          requested_at: requestedAt,
          metadata: data.metadata ?? null,
        },
        sharedContext,
      )
    }

    return {
      ...(stripProviderMetadata(verification as unknown as AuthTypes.RequestAuthVerificationResponse)),
      code,
      expires_at: expiresAt,
    }
  }

  async confirm(data: AuthTypes.ConfirmAuthVerificationDTO, sharedContext: Context = {}): Promise<AuthTypes.ConfirmAuthVerificationResponse> {
    if (!data.code) {
      throw new MedusaError(MedusaError.Types.INVALID_DATA, 'Verification code is required')
    }

    // Reject non-numeric / wrong-length codes up front so the digest comparison
    // below never runs against garbage. A 6-digit code is mandatory.
    const normalized = normalizeCode(data.code)
    if (normalized === null) {
      throw new MedusaError(MedusaError.Types.NOT_ALLOWED, 'Verification code is invalid or already used')
    }

    const digest = digestCode(this.hmacKey_, normalized)
    const rows = await this.authVerificationService_.list(
      { provider_metadata: { code_hash: digest } },
      {},
      sharedContext,
    )

    const verification = rows[0]
    if (!verification || verification.verified_at) {
      throw new MedusaError(MedusaError.Types.NOT_ALLOWED, 'Verification code is invalid or already used')
    }

    if (data.code_provider && data.code_provider !== verification.code_provider) {
      throw new MedusaError(
        MedusaError.Types.NOT_ALLOWED,
        `Verification code does not belong to provider "${data.code_provider}"`,
      )
    }

    const expiresAt = new Date(verification.requested_at).getTime() + this.ttlMs_()
    if (expiresAt <= Date.now()) {
      throw new MedusaError(MedusaError.Types.NOT_ALLOWED, 'Verification code has expired')
    }

    // Atomic one-time claim. The list→check→update sequence above is necessarily
    // racy (the built-in token provider has the same check-then-update race), so
    // the final write must be a single conditional UPDATE that only flips
    // `verified_at` when it is still NULL. Two concurrent confirms of the same
    // code therefore cannot both succeed: the second conditional update affects
    // zero rows and is rejected as already-used.
    const verifiedAt = new Date(Date.now())
    if (this.baseRepository_) {
      const manager = this.baseRepository_.getActiveManager(sharedContext)
      const affected = await manager.nativeUpdate(
        AuthVerification,
        { id: verification.id, verified_at: null },
        { verified_at: verifiedAt },
      )
      if (affected === 0) {
        throw new MedusaError(MedusaError.Types.NOT_ALLOWED, 'Verification code is invalid or already used')
      }
      return {
        ...(verification as unknown as AuthTypes.ConfirmAuthVerificationResponse),
        verified_at: verifiedAt,
      }
    }

    // Fallback for contexts where the ORM base repository is unavailable (the
    // isolated unit harness injects only `authVerificationService`). It keeps the
    // non-atomic behaviour but is never the production path.
    return await this.authVerificationService_.update(
      {
        id: verification.id,
        verified_at: verifiedAt,
      },
      sharedContext,
    ) as unknown as AuthTypes.ConfirmAuthVerificationResponse
  }
}

export default OtpVerificationProvider
